'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

def fibonacciseq():
    twoagonum = 1
    prevnum = 2
    newnum = 0
    fib_list = [twoagonum, prevnum]
    while True:
        newnum = twoagonum + prevnum
        if newnum < 4000000:
            fib_list.append(newnum)
        else:
            break
        twoagonum = prevnum
        prevnum = newnum
    return fib_list

def onlyevens(usr_list):
    new_list = []
    for each in usr_list:
        if each % 2 == 0:
            new_list.append(each)
    return new_list

print(sum(onlyevens(fibonacciseq())))